apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-args
        image: knightdoom/tardy:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: {{ .Release.Name }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/temp
          name: {{ .Release.Name }}-config
        - mountPath: /root/Music
          name: musicRoot
          subPath: {{ .Values.persistence.musicFolderSubPath }}
        - mountPath: /root/.config/zotify
          name: download_lists
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 300
      volumes:
      - name: {{ .Release.Name }}-config
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.configPVCName }}
      - name: musicRoot
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.musicFolderPVCName }}
      - configMap:
          defaultMode: 420
          items:
          - key: config.json
            path: config.json
          - key: downloads.txt
            path: downloads.txt
          name: {{ .Release.Name }}-settings
        name: download_lists
